
package group.intellect.creditpipeline.singleservicehr.soap;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SingleServiceHrWsImplService", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", wsdlLocation = "18072single-service-hr.wsdl")
public class SingleServiceHrWsImplService
    extends Service
{

    private final static URL SINGLESERVICEHRWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SINGLESERVICEHRWSIMPLSERVICE_EXCEPTION;
    private final static QName SINGLESERVICEHRWSIMPLSERVICE_QNAME = new QName("http://soap.singleservicehr.creditpipeline.intellect.group/", "SingleServiceHrWsImplService");

    static {
        SINGLESERVICEHRWSIMPLSERVICE_WSDL_LOCATION = SingleServiceHrWsImplService.class.getResource("18072single-service-hr.wsdl");
        WebServiceException e = null;
        if (SINGLESERVICEHRWSIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '18072single-service-hr.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SINGLESERVICEHRWSIMPLSERVICE_EXCEPTION = e;
    }

    public SingleServiceHrWsImplService() {
        super(__getWsdlLocation(), SINGLESERVICEHRWSIMPLSERVICE_QNAME);
    }

    public SingleServiceHrWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SINGLESERVICEHRWSIMPLSERVICE_QNAME, features);
    }

    public SingleServiceHrWsImplService(URL wsdlLocation) {
        super(wsdlLocation, SINGLESERVICEHRWSIMPLSERVICE_QNAME);
    }

    public SingleServiceHrWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SINGLESERVICEHRWSIMPLSERVICE_QNAME, features);
    }

    public SingleServiceHrWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SingleServiceHrWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SingleServiceHrWs
     */
    @WebEndpoint(name = "SingleServiceHrWsImplPort")
    public SingleServiceHrWs getSingleServiceHrWsImplPort() {
        return super.getPort(new QName("http://soap.singleservicehr.creditpipeline.intellect.group/", "SingleServiceHrWsImplPort"), SingleServiceHrWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SingleServiceHrWs
     */
    @WebEndpoint(name = "SingleServiceHrWsImplPort")
    public SingleServiceHrWs getSingleServiceHrWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.singleservicehr.creditpipeline.intellect.group/", "SingleServiceHrWsImplPort"), SingleServiceHrWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SINGLESERVICEHRWSIMPLSERVICE_EXCEPTION!= null) {
            throw SINGLESERVICEHRWSIMPLSERVICE_EXCEPTION;
        }
        return SINGLESERVICEHRWSIMPLSERVICE_WSDL_LOCATION;
    }

}
