
package group.intellect.creditpipeline.singleservicehr.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SingleServiceHrWs", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SingleServiceHrWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns group.intellect.creditpipeline.singleservicehr.soap.EmployeeCreationResponce
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateEmployee")
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateEmployeeResponse")
    public EmployeeCreationResponce createEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeCreationRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns group.intellect.creditpipeline.singleservicehr.soap.SubdivisionCreationResponce
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSubdivision", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateSubdivision")
    @ResponseWrapper(localName = "createSubdivisionResponse", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateSubdivisionResponse")
    public SubdivisionCreationResponce createSubdivision(
        @WebParam(name = "arg0", targetNamespace = "")
        SubdivisionCreationRequest arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns group.intellect.creditpipeline.singleservicehr.soap.UserCreationResponce
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.singleservicehr.creditpipeline.intellect.group/", className = "group.intellect.creditpipeline.singleservicehr.soap.CreateUserResponse")
    public UserCreationResponce createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserCreationRequest arg0);

}
